# Generated by Django 5.2.7 on 2026-09-03 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('model_name', models.CharField(max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_concurrent_sessions', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('session_lifetime_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)])),
                ('inactivity_timeout_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('refresh_token_lifetime_days', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_failed_logins', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('lockout_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('enforce_ip_allowlist', models.BooleanField(default=False)),
                ('allowed_ip_cidrs', models.TextField(blank=True, help_text='One CIDR per line. Only used when the allowlist is enforced.')),
                ('tenant', models.OneToOneField(blank=True, help_text='Leave empty for the platform-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='adminconfig.tenant')),
            ],
            options={
                'verbose_name_plural': 'Security policies',
            },
        ),
        migrations.CreateModel(
            name='ReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_title', models.CharField(default='Edge Telemetry Diagnostic Report', max_length=120)),
                ('footer_note', models.CharField(blank=True, max_length=255)),
                ('include_thresholds', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_validation_summary', models.BooleanField(default=True)),
                ('timestamp_mode', models.CharField(choices=[('utc', 'UTC only'), ('local', 'Browser local only'), ('both', 'UTC and browser local')], default='both', max_length=10)),
                ('stale_data_minutes', models.PositiveIntegerField(default=60, help_text='A value older than this is reported with degraded data quality.', validators=[django.core.validators.MinValueValidator(1)])),
                ('missing_threshold_text', models.CharField(default='Threshold needs to be defined.', max_length=160)),
                ('tenant', models.OneToOneField(blank=True, help_text='Leave empty for the platform-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_setting', to='adminconfig.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='adminconfig.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SSHPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_pattern', models.CharField(help_text='Host or glob pattern, e.g. edge-*.site.internal', max_length=160)),
                ('remote_username', models.CharField(blank=True, max_length=64)),
                ('access_level', models.CharField(choices=[('none', 'No access'), ('read', 'Read only'), ('operate', 'Operate'), ('admin', 'Administrative')], default='read', max_length=10)),
                ('is_enabled', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_ssh_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_permissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssh_permissions', to='adminconfig.tenant')),
            ],
            options={
                'ordering': ['user__username', 'host_pattern'],
                'constraints': [models.UniqueConstraint(fields=('user', 'host_pattern'), name='uniq_ssh_user_host')],
            },
        ),
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(choices=[('wifi_signal', 'SCC - Wi-Fi Signal Strength'), ('cellular_signal_strength', 'SCC - Cellular Signal Strength'), ('etp_connection_status', 'ETP - ETP Connection Status'), ('inverter_operating_state', 'INV - Inverter Operating State'), ('bgcs_relay_status', 'BGCS - BGCS Grid Relay Status'), ('pv1_voltage', 'PV - PV1 Voltage'), ('pv2_voltage', 'PV - PV2 Voltage'), ('pv3_voltage', 'PV - PV3 Voltage'), ('pv4_voltage', 'PV - PV4 Voltage'), ('pv1_current', 'PV - PV1 Current'), ('pv2_current', 'PV - PV2 Current'), ('pv3_current', 'PV - PV3 Current'), ('pv4_current', 'PV - PV4 Current'), ('pv1_power', 'PV - PV1 Power'), ('pv2_power', 'PV - PV2 Power'), ('pv3_power', 'PV - PV3 Power'), ('pv4_power', 'PV - PV4 Power'), ('grid_voltage_l1', 'GRID - Grid Voltage RMS L1'), ('grid_voltage_l2', 'GRID - Grid Voltage RMS L2'), ('grid_current_l1', 'GRID - Grid Current RMS L1'), ('grid_current_l2', 'GRID - Grid Current RMS L2'), ('grid_frequency_total', 'GRID - Grid Frequency Total'), ('grid_power', 'GRID - Grid Power'), ('load_voltage_l1', 'LOAD - Load Voltage RMS L1'), ('load_voltage_l2', 'LOAD - Load Voltage RMS L2'), ('load_current_l1', 'LOAD - Load Current RMS L1'), ('load_current_l2', 'LOAD - Load Current RMS L2'), ('load_frequency_total', 'LOAD - Load Frequency Total'), ('load_power', 'LOAD - Load Power'), ('battery_voltage', 'BMS - Battery Voltage (DC bus)'), ('battery1_voltage', 'BMS - Battery 1 Voltage'), ('battery2_voltage', 'BMS - Battery 2 Voltage'), ('battery3_voltage', 'BMS - Battery 3 Voltage'), ('battery1_current', 'BMS - Battery 1 Current'), ('battery2_current', 'BMS - Battery 2 Current'), ('battery3_current', 'BMS - Battery 3 Current'), ('battery1_soc', 'BMS - Battery 1 State of Charge'), ('battery2_soc', 'BMS - Battery 2 State of Charge'), ('battery3_soc', 'BMS - Battery 3 State of Charge'), ('battery1_temp', 'BMS - Battery 1 Temperature'), ('battery2_temp', 'BMS - Battery 2 Temperature'), ('battery3_temp', 'BMS - Battery 3 Temperature'), ('battery1_power', 'BMS - Battery 1 Power'), ('battery2_power', 'BMS - Battery 2 Power'), ('battery3_power', 'BMS - Battery 3 Power'), ('battery_main_relay', 'BMS - Battery Main Relay Error'), ('battery_heater_status', 'BMS - Battery Heater Status')], db_index=True, max_length=80)),
                ('lower_limit', models.FloatField(blank=True, null=True)),
                ('upper_limit', models.FloatField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Show the reference lines by default on the chart card.')),
                ('is_protected', models.BooleanField(default=True, help_text='Protected defaults can only be changed by administrators.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_thresholds', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave empty for the platform-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='adminconfig.tenant')),
            ],
            options={
                'ordering': ['metric_key'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'metric_key'), name='uniq_threshold_tenant_metric'), models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('metric_key',), name='uniq_threshold_global_metric')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave empty for the platform-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='adminconfig.tenant')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_flag_tenant_key'), models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('key',), name='uniq_flag_global_key')],
            },
        ),
        migrations.CreateModel(
            name='AccessControlRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(choices=[('dashboard', 'Dashboard'), ('events', 'Events & analytics'), ('history', 'History charts'), ('validation_report', 'Validation report'), ('pdf_report', 'PDF report'), ('thresholds', 'Threshold configuration'), ('admin_console', 'Admin console'), ('adx_query', 'Raw ADX query'), ('ssh', 'SSH access')], max_length=40)),
                ('can_view', models.BooleanField(default=True)),
                ('can_export', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='auth.group')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='adminconfig.tenant')),
            ],
            options={
                'ordering': ['resource', 'group__name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'group', 'resource'), name='uniq_access_rule')],
            },
        ),
    ]
