# Generated by Django 5.0.14 on 2026-09-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricthreshold',
            name='failed_states',
            field=models.JSONField(blank=True, default=list, help_text='State metrics only: values classified as Failed.'),
        ),
        migrations.AddField(
            model_name='metricthreshold',
            name='passed_states',
            field=models.JSONField(blank=True, default=list, help_text='State metrics only: values classified as Passed.'),
        ),
    ]
