# Generated by Django 5.2.7 on 2025-11-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_grid_L1_V_RMS', models.FloatField(help_text='Voltage RMS for L1 (V)')),
                ('inverter_grid_L2_V_RMS', models.FloatField(help_text='Voltage RMS for L2 (V)')),
                ('inverter_grid_L1_I_RMS', models.FloatField(help_text='Current RMS for L1 (A)')),
                ('BGCS_RELAY_STATUS', models.CharField(help_text='Relay status (e.g., ON/OFF)', max_length=50)),
                ('ETP_CONTAINER_STATUS', models.CharField(help_text='Container status', max_length=50)),
                ('WIFI_SIGNAL_STRENGTH', models.IntegerField(help_text='Signal strength in dBm')),
                ('WIFI_FREQ_BAND', models.CharField(help_text='Wi-Fi frequency band (e.g., 2.4GHz, 5GHz)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
